-- Catalog seeds for the multi-provider inference router (docs/architecture/
-- multi-provider-inference-implementation.md) and ADR-explicit-device-local-models.md.
--
-- Three on-device models (execution target "browser-local", provider "local"): each one names an
-- entry in the pinned @mlc-ai/web-llm package's own prebuilt model list, and the web client only
-- ever loads such entries from the approved https://huggingface.co/mlc-ai/ origin. They cost
-- nothing to run (pricing 0) and never send conversation text to a cloud model.
--
-- One Soko Cloud entry (Qwen3-4B on Soko's own llama.cpp server) seeded *disabled*: it only works
-- after an operator sets SOKO_LLAMA_BASE_URL and flips `available` / `inference.enabled` through
-- PUT /v1/platform/model-catalog/:id.
--
-- Commercial vendor models (OpenAI, Anthropic, Z.ai) are deliberately not seeded: their model ids
-- and prices change and must be verified by the operator registering them.
--
-- `on conflict do nothing`: an operator's existing row with the same id is never overwritten.
insert into cp2_model_catalog (entity_id, record, updated_at) values
  ('smollm2-360m-device', '{"id":"smollm2-360m-device","label":"SmolLM2 360M (on this device)","provider":"local","description":"Runs privately on your own phone or computer (WebGPU). Smallest and fastest to download; best for short replies. Nothing is sent to a cloud model.","capabilities":["chat","on-device","english"],"available":true,"source":"huggingface","format":"remote","license":"Apache-2.0","licenseUrl":"https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct/blob/main/LICENSE","modelCardUrl":"https://huggingface.co/mlc-ai/SmolLM2-360M-Instruct-q4f16_1-MLC","downloadUrl":null,"fileName":null,"fileSizeBytes":394000000,"minimumMemoryGb":2,"recommended":false,"contextWindow":4096,"canonicalModelId":"SmolLM2-360M-Instruct-q4f16_1-MLC","supportsToolCalling":false,"supportsStructuredOutput":true,"inference":{"providerId":"local","providerModelId":"SmolLM2-360M-Instruct-q4f16_1-MLC","executionTarget":"browser-local","capabilities":{"text":true,"structuredOutput":true,"streaming":true},"maxOutputTokens":512,"enabled":true,"pricing":{"inputPerMillionTokens":0,"outputPerMillionTokens":0,"currency":"USD"}}}'::jsonb, now()),
  ('qwen2.5-0.5b-device', '{"id":"qwen2.5-0.5b-device","label":"Qwen2.5 0.5B (on this device)","provider":"local","description":"Runs privately on your own phone or computer (WebGPU). Multilingual, a good balance of size and quality. Nothing is sent to a cloud model.","capabilities":["chat","on-device","multilingual"],"available":true,"source":"huggingface","format":"remote","license":"Apache-2.0","licenseUrl":"https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct/blob/main/LICENSE","modelCardUrl":"https://huggingface.co/mlc-ai/Qwen2.5-0.5B-Instruct-q4f16_1-MLC","downloadUrl":null,"fileName":null,"fileSizeBytes":990000000,"minimumMemoryGb":3,"recommended":true,"contextWindow":4096,"canonicalModelId":"Qwen2.5-0.5B-Instruct-q4f16_1-MLC","supportsToolCalling":false,"supportsStructuredOutput":true,"inference":{"providerId":"local","providerModelId":"Qwen2.5-0.5B-Instruct-q4f16_1-MLC","executionTarget":"browser-local","capabilities":{"text":true,"structuredOutput":true,"streaming":true},"maxOutputTokens":512,"enabled":true,"pricing":{"inputPerMillionTokens":0,"outputPerMillionTokens":0,"currency":"USD"}}}'::jsonb, now()),
  ('qwen3-1.7b-device', '{"id":"qwen3-1.7b-device","label":"Qwen3 1.7B (on this device)","provider":"local","description":"Runs privately on your own computer or a high-end phone (WebGPU, about 2 GB). The most capable on-device option. Nothing is sent to a cloud model.","capabilities":["chat","on-device","multilingual","reasoning"],"available":true,"source":"huggingface","format":"remote","license":"Apache-2.0","licenseUrl":"https://huggingface.co/Qwen/Qwen3-1.7B/blob/main/LICENSE","modelCardUrl":"https://huggingface.co/mlc-ai/Qwen3-1.7B-q4f16_1-MLC","downloadUrl":null,"fileName":null,"fileSizeBytes":2136000000,"minimumMemoryGb":6,"recommended":false,"contextWindow":4096,"canonicalModelId":"Qwen3-1.7B-q4f16_1-MLC","supportsToolCalling":false,"supportsStructuredOutput":true,"inference":{"providerId":"local","providerModelId":"Qwen3-1.7B-q4f16_1-MLC","executionTarget":"browser-local","capabilities":{"text":true,"structuredOutput":true,"streaming":true,"reasoning":true},"maxOutputTokens":768,"enabled":true,"pricing":{"inputPerMillionTokens":0,"outputPerMillionTokens":0,"currency":"USD"}}}'::jsonb, now()),
  ('qwen3-4b-soko-cloud', '{"id":"qwen3-4b-soko-cloud","label":"Qwen3-4B (Soko Cloud)","provider":"soko-llama","description":"Qwen3-4B served by Soko''s own llama.cpp inference server. Available once an operator configures SOKO_LLAMA_BASE_URL and enables this entry.","capabilities":["chat","multilingual","reasoning"],"available":false,"source":"hosted","format":"remote","license":"Apache-2.0","licenseUrl":"https://huggingface.co/Qwen/Qwen3-4B/blob/main/LICENSE","modelCardUrl":"https://huggingface.co/Qwen/Qwen3-4B","downloadUrl":null,"fileName":null,"fileSizeBytes":null,"minimumMemoryGb":null,"recommended":false,"contextWindow":32768,"canonicalModelId":"Qwen/Qwen3-4B","supportsToolCalling":false,"supportsStructuredOutput":false,"inference":{"providerId":"soko-llama","providerModelId":"qwen3-4b","executionTarget":"remote-inference","capabilities":{"text":true,"streaming":true,"reasoning":true},"maxOutputTokens":1024,"enabled":false,"pricing":null}}'::jsonb, now())
on conflict (entity_id) do nothing;
