import type { AgentTurnStreamEvent, DeviceInferenceJob } from "@soko/shared-types";
import { createRuntimeReplyTextStream } from "@soko/tool-core";

import type { runDeviceGeneration } from "../device-model-engine";
import {
  currentDeviceRuntime,
  isDeviceInferenceSupported,
  listInstalledDeviceModels
} from "../device-models";
import { readApiBaseUrl } from "../lib/api";

/**
 * Runs alongside one agent turn request (POST /v1/messages or /runtime/turns):
 *
 * 1. Live preview: reads GET /v1/ai/turn-stream/:turnId and reports the reply text as it is
 *    generated by any hosted model (Vercel, OpenAI, Anthropic, Z.ai, llama.cpp...). The chat needs
 *    no vendor-specific logic - the server already reduced every vendor to plain reply text.
 * 2. On-device generation: when this device has on-device models installed, it claims the turn's
 *    device job (if the shop's model is one of them), runs it locally, previews the tokens as they
 *    come, and returns the output to the server.
 *
 * The preview is never the reply of record: the turn response (validated server-side) replaces it.
 */
export interface AgentTurnCompanion {
  turnId: string;
  /** Send with the turn request so the server can associate stream and device job. */
  headers: Record<string, string>;
  stop(): void;
}

export interface AgentTurnCompanionOptions {
  /** Defaults to a fresh random id. */
  turnId?: string;
  onPreview: (text: string) => void;
  onDeviceActivity?: (activity: "generating" | "done" | "failed") => void;
  fetchImpl?: typeof fetch;
  baseUrl?: string;
  /** Test hook: which on-device models this device can run. */
  installedModels?: () => string[];
  deviceSupported?: () => boolean;
  generate?: typeof runDeviceGeneration;
}

export function startAgentTurnCompanion(options: AgentTurnCompanionOptions): AgentTurnCompanion {
  const turnId = options.turnId ?? crypto.randomUUID();
  const controller = new AbortController();
  const doFetch = options.fetchImpl ?? fetch;
  const base = options.baseUrl ?? readApiBaseUrl();
  let preview = "";
  const emit = (text: string) => {
    preview = text;
    options.onPreview(preview);
  };

  void readTurnStream(doFetch, base, turnId, controller.signal, (event) => {
    if (event.type === "text") emit(preview + event.text);
    if (event.type === "reset") emit("");
  });

  const installed = (options.installedModels ?? listInstalledDeviceModels)();
  if (installed.length > 0 && (options.deviceSupported ?? isDeviceInferenceSupported)()) {
    void serveDeviceJobs({
      doFetch,
      base,
      turnId,
      installed,
      signal: controller.signal,
      generate: options.generate ?? generateLazily,
      onPreview: emit,
      ...(options.onDeviceActivity === undefined ? {} : { onActivity: options.onDeviceActivity })
    });
  }

  return {
    turnId,
    headers: { "x-soko-turn-id": turnId },
    stop: () => controller.abort()
  };
}

async function readTurnStream(
  doFetch: typeof fetch,
  base: string,
  turnId: string,
  signal: AbortSignal,
  onEvent: (event: AgentTurnStreamEvent) => void
): Promise<void> {
  try {
    const response = await doFetch(`${base}/v1/ai/turn-stream/${encodeURIComponent(turnId)}`, {
      credentials: "include",
      headers: { accept: "text/event-stream" },
      signal
    });
    if (!response.ok || response.body === null) return;
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    for (;;) {
      const { done, value } = await reader.read();
      if (done) return;
      buffer += decoder.decode(value, { stream: true });
      let boundary = buffer.indexOf("\n\n");
      while (boundary !== -1) {
        const frame = buffer.slice(0, boundary);
        buffer = buffer.slice(boundary + 2);
        for (const line of frame.split("\n")) {
          if (!line.startsWith("data: ")) continue;
          try {
            onEvent(JSON.parse(line.slice(6)) as AgentTurnStreamEvent);
          } catch {
            // Ignore a malformed frame; the turn response is authoritative anyway.
          }
        }
        boundary = buffer.indexOf("\n\n");
      }
    }
  } catch {
    // Aborted when the turn finished, or the stream is unavailable: the preview is optional.
  }
}

async function serveDeviceJobs(input: {
  doFetch: typeof fetch;
  base: string;
  turnId: string;
  installed: string[];
  signal: AbortSignal;
  generate: typeof runDeviceGeneration;
  onPreview: (text: string) => void;
  onActivity?: (activity: "generating" | "done" | "failed") => void;
}): Promise<void> {
  const query = new URLSearchParams({
    runtime: currentDeviceRuntime(),
    models: input.installed.join(","),
    turnId: input.turnId,
    waitMs: "20000"
  });
  while (!input.signal.aborted) {
    let job: DeviceInferenceJob;
    try {
      const response = await input.doFetch(
        `${input.base}/v1/ai/device-inference/jobs/next?${query.toString()}`,
        { credentials: "include", signal: input.signal }
      );
      if (response.status === 204) {
        // The server already long-polls; this pause only guards against a tight loop if a 204
        // ever comes back early (proxy timeout, server restart).
        await pause(500, input.signal);
        continue;
      }
      if (!response.ok) return;
      job = ((await response.json()) as { job: DeviceInferenceJob }).job;
    } catch {
      return;
    }
    input.onActivity?.("generating");
    const extractor = createRuntimeReplyTextStream();
    let visible = "";
    const post = (path: string, body: Record<string, unknown>) =>
      input.doFetch(
        `${input.base}/v1/ai/device-inference/jobs/${encodeURIComponent(job.id)}/${path}`,
        {
          method: "POST",
          credentials: "include",
          headers: { "content-type": "application/json" },
          body: JSON.stringify(body)
        }
      );
    try {
      const result = await input.generate(
        job,
        (delta) => {
          const text = extractor.push(delta);
          if (text !== "") {
            visible += text;
            input.onPreview(visible);
          }
        },
        input.signal
      );
      await post("result", {
        token: job.token,
        text: result.text,
        ...(result.usage === undefined ? {} : { usage: result.usage }),
        latencyMs: result.latencyMs,
        ...(result.firstTokenMs === undefined ? {} : { firstTokenMs: result.firstTokenMs })
      });
      input.onActivity?.("done");
    } catch {
      await post("failure", { token: job.token }).catch(() => undefined);
      input.onActivity?.("failed");
    }
  }
}

function pause(ms: number, signal: AbortSignal): Promise<void> {
  return new Promise((resolve) => {
    const timer = setTimeout(resolve, ms);
    signal.addEventListener(
      "abort",
      () => {
        clearTimeout(timer);
        resolve();
      },
      { once: true }
    );
  });
}

/** The engine (and WebLLM) load only when this device actually runs a job. */
const generateLazily: typeof runDeviceGeneration = async (job, onDelta, signal) =>
  (await import("../device-model-engine")).runDeviceGeneration(job, onDelta, signal);
